area51/pinateria/pedidos/urls.py
from django.urls import path

from pedidos.views import Generar

urlpatterns = [
    path('generar/<int:pk>/', Generar.as_view(), name='generar'),
]

area51/pinateria/pinateria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('productos/', include('productos.urls')),
    path('pedidos/', include('pedidos.urls')),
    path('', include('website.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

area51/pinateria/pedidos/models.py
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator
from django.db import models

from productos.models import Producto


class Pedido(models.Model):
    usuario = models.ForeignKey(
        User,
        models.CASCADE,
        blank=False,
        null=False
    )

    producto = models.ForeignKey(
        Producto,
        models.CASCADE,
        blank=False,
        null=False
    )

    cantidad = models.PositiveIntegerField(
        blank=False,
        null=False,
        validators=[MinValueValidator(1)]
    )

    estado = models.CharField(
        max_length=10,
        choices=(
            ('proceso', 'En proceso'),
            ('confirmado', 'Confirmado'),
            ('enviado', 'Enviado'),
            ('recibido', 'Recibido'),
            ('cancelado', 'Cancelado'),
        ),
        default='proceso',
        null=False
    )

    fecha_emision = models.DateTimeField(
        auto_now_add=True
    )

    fecha_actualizacion = models.DateTimeField(
        auto_now=True
    )

    @property
    def codigo(self):
        return 'PRO{:04d}'.format(self.id)

    def __str__(self):
        return self.codigo

area51/pinateria/productos/models.py
from django.db import models


class Categoria(models.Model):
    nombre = models.CharField(
        max_length=15,
        blank=False,
        null=False
    )

    def __str__(self):
        return self.nombre


class Producto(models.Model):
    categoria = models.ForeignKey(
        Categoria,
        on_delete=models.CASCADE,
        blank=False,
        null=False,
    )

    personaje = models.CharField(
        max_length=40,
        blank=False,
        null=False
    )

    nombre_comercial = models.CharField(
        max_length=50,
        blank=True,
        null=True
    )

    descripcion = models.TextField(
        blank=True,
        null=True
    )

    precio = models.DecimalField(
        max_digits=15,
        decimal_places=5,
        blank=False,
        null=False
    )

    def __str__(self):
        return self.personaje


class ImagenProducto(models.Model):
    producto = models.ForeignKey(
        Producto,
        models.CASCADE,
        blank=False,
        null=False,
        # related_name='imagenes'
    )

    imagen = models.ImageField(
        upload_to='productos',
        blank=False,
        null=False
    )

    def __str__(self):
        return self.producto.personaje

area51/pinateria/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block titulo %}Piñatería AREA 51{% endblock %}</title>
</head>
<body>
    <h1>Piñatería AREA 51</h1>

    <h4>Navegación</h4>
    <ul>
        <li><a href="{% url 'portada' %}">Home</a></li>
        <li><a href="{% url 'buscar' %}">Buscar</a></li>
        {% if user.is_authenticated %}
            <li><a href="{% url 'perfil' %}">{{ user.username }} (perfil)</a></li>
            <li><a href="{% url 'logout' %}">Logout</a></li>
        {% else %}
            <li><a href="{% url 'login' %}">Login</a></li>
            <li><a href="{% url 'registro' %}">Registro</a></li>
        {% endif %}
    </ul>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    {% block contenido %}{% endblock %}

    <p>&copy; 2018 - AREA 51</p>
</body>
</html>

area51/pinateria/templates/buscar.html
{% extends 'base.html' %}

{% block contenido %}
    <form action="">
        <input type="text" name="termino" value="{{ request.GET.termino }}">
        <input type="submit" value="Buscar">
    </form>

    <h1>Resultados</h1>
    <ul>
        {% for producto in object_list %}
            <li><a href="{% url 'detalle' producto.pk %}">{{ producto.personaje }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

area51/pinateria/templates/detalle.html
{% extends 'base.html' %}

{% block titulo %}{{ producto.personaje }}{% endblock %}
{% block contenido %}
    <h2>{{ producto.personaje }}</h2>
    <h4>Comercialmente: {{ producto.nombre_comercial }}</h4>
    <p>{{ producto.descripcion|linebreaksbr }}</p>
    <h4>Precio: S/ {{ producto.precio|floatformat:2 }}</h4>
    <h4>Imágenes:</h4>
    <ul>
        {% for imagen in producto.imagenproducto_set.all %}
        <li><img src="{{ imagen.imagen.url }}" width="100"></li>
        {% endfor %}
    </ul>

    <a href="{% url 'generar' producto.pk %}">Pedir este producto</a>

{% endblock %}

area51/pinateria/templates/generar.html
{% extends 'base.html' %}

{% block titulo %}Pedido{% endblock %}

{% block contenido %}
    <h1>Pedido</h1>
    <h2>Producto: {{ producto.personaje }}</h2>
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Enviar Pedido">
    </form>
{% endblock %}

area51/pinateria/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block contenido %}
    <img src="{% static 'gatito.jpg' %}" width="300">

    <h4>Últimos productos:</h4>
    <ul>
        {% for producto in productos %}
            <li><a href="{% url 'detalle' producto.pk %}">{{ producto.personaje }}: S/ {{ producto.precio|floatformat:2 }}</a></li>
        {% endfor %}
    </ul>

{#    {% if edad > 18 %}#}
{#        <h3>Mayor de edad</h3>#}
{#    {% else %}#}
{#        <h3>Menor de edad</h3>#}
{#    {% endif %}#}
{% endblock %}

area51/pinateria/templates/login.html
{% extends 'base.html' %}

{% block titulo %}Login{% endblock %}

{% block contenido %}
    <h1>Login</h1>
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Login">
    </form>
{% endblock %}

area51/pinateria/templates/perfil.html
{% extends 'base.html' %}

{% block titulo %}Perfil{% endblock %}

{% block contenido %}
    <h1>Perfil</h1>
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Guardar">
    </form>

    <h2>Últimos pedidos</h2>
    <table>
        <thead>
            <tr>
                <th>Código</th>
                <th>Producto</th>
                <th>Cantidad</th>
                <th>Fecha</th>
                <th>Estado</th>
            </tr>
        </thead>
        <tbody>
            {% for pedido in pedidos %}
            <tr>
                <td>{{ pedido.codigo }}</td>
                <td>{{ pedido.producto.nombre_comercial }}</td>
                <td>{{ pedido.cantidad }}</td>
                <td>{{ pedido.fecha_emision }}</td>
                <td>{{ pedido.get_estado_display }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

area51/pinateria/templates/registro.html
{% extends 'base.html' %}

{% block titulo %}Regístrate!{% endblock %}

{% block contenido %}
    <h1>Registro</h1>
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Registro">
    </form>
{% endblock %}